spring.application.name=fitness-finder-backend

spring.datasource.url= jdbc:postgresql://localhost:5432/finess_finder
spring.datasource.username=postgres
spring.datasource.password=tiger

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.port=8082

# JWT Secret (Keep secure!)
jwt.secret=mySecretKeyMustBeAtLeast64CharactersLongForHS256Algorithm12345678901234567890
jwt.expiration=86400000

